### ISSUE TITLE
Help to use the Tutorial

### ISSUE THREAD

**Issue by ofilangi** [zazuko/trifid#78]
I tried to follow the [tutorial](https://github.com/zazuko/trifid/blob/master/Tutorial.md)
with e simple config file :
```json
{   
    "baseConfig": "trifid:config-sparql.json", 
    "sparqlEndpointUrl": "http://dbpedia.org/sparql",
}   
```
and the command 
```sh
docker run -ti -e TRIFID_CONFIG=config-custom.json -v $(pwd)/config-custom.json:/usr/src/app/config-custom.json -p 8080:8080 zazuko/trifid
```
The mail page (http://localhost:8080/) have no information/links to browse the Dbpedia SPARQL endpoint...

![image](https://user-images.githubusercontent.com/16104110/76973262-fd2a2b00-692f-11ea-8633-ddc96c04fb2f.png)
```
> trifid@2.3.3 start /app
> node server.js

::ffff:172.17.0.1 - - [18/Mar/2020:14:49:53 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.87 Chrome/80.0.3987.87 Safari/537.36"
::ffff:172.17.0.1 - - [18/Mar/2020:14:49:53 +0000] "GET /favicon.ico HTTP/1.1" 200 - "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.87 Chrome/80.0.3987.87 Safari/537.36"
``` 
How can I have an access to the YASGUI or an Dbpedia entity start point ?

**Comment by ktk** [comment]
I will have to update this documentation, but did you try /sparql on localhost?

regards

Adrian

**Comment by ofilangi** [comment]
I did a test with this docker-compose yml file (I used your docker image in this test  zazuko/trifid) 
```
version: '3'
services:
    virtuoso:
      image: tenforce/virtuoso
      environment:
          DBA_PASSWORD: "test"
          SPARQL_UPDATE: "false"
          DEFAULT_GRAPH: "http://www.tesgraph.org#"
      ports:
          - 8890:8890
    
    trifid:
      image:  zazuko/trifid
      volumes:
        - ./config-custom.json:/usr/src/app/config-custom.json
      environment:
        - TRIFID_CONFIG=config-custom.json
      ports:
        - 8080:8080
```
config-custome.json 
```
{
    "baseConfig": "trifid:config-sparql.json", 
    "sparqlEndpointUrl": "http://virtuoso:8890/sparql"
}
```
I loaded a simple turtle file on my localhost (http://localhost:8890) [the file](https://gist.githubusercontent.com/kal/ee1260ceb462d8e0d5bb/raw/1364c2bb469af53323fdda508a6a579ea60af6e4/log_sample.ttl)

I see this simple page when I'm go on http://localhost:8080/
![image](https://user-images.githubusercontent.com/16104110/77076586-4f348480-69f4-11ea-8dc3-819c4f908cb0.png)

Did i forget to configure something ?
